# Generated by Django 5.0.4 on 2024-05-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_customuser_student_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='student_id_card',
        ),
    ]
