# Generated by Django 5.0.4 on 2024-06-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_name_chatroom_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
