# Generated by Django 5.0.4 on 2024-06-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='charge',
            field=models.IntegerField(default=0),
        ),
    ]
