# Generated by Django 5.0.4 on 2024-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatroom_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id_file',
            field=models.ImageField(blank=True, null=True, upload_to='student_ids/'),
        ),
    ]
